const detail=(overview,principle,applications,advantages,limitations,learning,resources)=>({overview,principle,applications,advantages,limitations,learning,resources});

export const robots=[
{id:'atlas',name:'Atlas',type:'Humanoid',application:'Industrial mobility',difficulty:'Advanced',icon:'◈',description:'A dynamic humanoid platform built for balance, manipulation and human-centric workspaces.',tags:['Humanoid','AI'],specs:{dof:'28+',sensors:'LiDAR · IMU · stereo vision',controller:'Real-time whole-body control',power:'Battery electric',payload:'20 kg nominal'},features:['Dynamic whole-body control','Terrain-aware perception','Force-sensitive manipulation'],...detail('Humanoid robots combine bipedal locomotion, compliant joints and dexterous hands to work around infrastructure designed for people.','A state estimator fuses cameras and inertial data; a model-predictive controller distributes forces across feet and hands while planning a stable center of mass.','Material handling, inspection, warehouse kitting and research in unstructured spaces.','Uses existing stairs, tools and workcells; expressive manipulation; rich research ecosystem.','High energy use, difficult balance recovery, expensive maintenance and strict safety validation.','Start with rigid-body transforms, then study inverse kinematics, whole-body control and contact planning.','ROS 2 · Pinocchio · Isaac Sim')},
{id:'spot',name:'Spot',type:'Legged',application:'Inspection & autonomy',difficulty:'Advanced',icon:'◎',description:'An agile quadruped that carries sensing payloads into places wheeled robots cannot reach.',tags:['Legged','Autonomous'],specs:{dof:'12',sensors:'Depth · IMU · cameras',controller:'Autonomy stack',power:'Rechargeable battery',runtime:'90 min typical'},features:['API-first autonomy','Self-righting mobility','Payload ecosystem'],...detail('A four-legged mobile base that keeps a stable footprint on stairs, gravel and industrial floors.','Gait generation selects footfall timing while visual-inertial odometry estimates the body pose for terrain-aware motion.','Plant inspection, construction surveys, security patrols and hazardous-area data collection.','Climbs uneven terrain; carries interchangeable payloads; can be teleoperated or scripted.','Limited runtime, payload and speed; requires careful mission planning around people.','Learn coordinate frames, state estimation, gait concepts and safety-rated teleoperation.','Spot SDK · ROS 2 bridge · terrain mapping')},
{id:'turtlebot',name:'TurtleBot 4',type:'Wheeled',application:'ROS2 education',difficulty:'Beginner',icon:'◉',description:'The approachable mobile base for learning ROS2, navigation and mapping hands-on.',tags:['Educational','ROS2'],specs:{dof:'2 drive + caster',sensors:'2D LiDAR · depth camera',controller:'Raspberry Pi 4',power:'Li-ion battery',runtime:'2–3 hours'},features:['Nav2 ready','Open-source ROS2 stack','Modular accessories'],...detail('A compact differential-drive robot that exposes the complete software loop from sensor topics to navigation goals.','Wheel encoders estimate odometry; SLAM combines scans and motion, then Nav2 plans and controls a collision-free trajectory.','Classroom labs, home mapping, ROS 2 prototypes and algorithm demonstrations.','Affordable, documented and repairable; the same concepts scale to larger bases.','Small payload, slippery floors and limited compute for heavy vision models.','Practice Linux, Python publishers, TF2, RViz, SLAM Toolbox and Nav2.','ROS 2 Jazzy · Nav2 · SLAM Toolbox')},
{id:'ur5',name:'UR5e',type:'Robotic Arm',application:'Assembly & research',difficulty:'Intermediate',icon:'⌁',description:'Collaborative six-axis arm for precise assembly, teaching and flexible automation.',tags:['Industrial','Arm'],specs:{dof:'6',sensors:'Joint torque feedback',controller:'Dedicated cabinet',power:'AC mains',reach:'850 mm'},features:['Force limiting','Tool center point control','Fast deployment'],...detail('A six-axis collaborative manipulator designed for repeatable work near people after a documented risk assessment.','Forward and inverse kinematics map joint angles to tool pose; trajectory interpolation limits speed, acceleration and force.','Pick-and-place, screwdriving, inspection, teaching and low-volume assembly.','Quick redeployment; intuitive teaching; accurate pose control.','Reach and payload are finite; collaborative mode is not a substitute for guarding or risk assessment.','Study frames, Jacobians, trajectory planning, end-effectors and industrial safety.','URScript · MoveIt 2 · ISO/TS 15066')},
{id:'perseverance',name:'Perseverance',type:'Space',application:'Planetary science',difficulty:'Expert',icon:'✦',description:'A resilient autonomous rover designed to navigate and investigate the Martian surface.',tags:['Space','Autonomous'],specs:{dof:'6 wheel drive',sensors:'Cameras · spectrometers',controller:'Radiation-hardened compute',power:'MMRTG',mission:'Mars 2020'},features:['Autonomous traverse','Sample caching','Long-range communications'],...detail('A planetary science platform built for long communication delays, extreme dust and terrain that cannot be repaired by humans.','Onboard hazard detection and visual odometry allow short autonomous drives; scientists validate longer sequences from Earth.','Geology, sample caching, atmospheric measurements and technology demonstrations.','Redundant systems; carefully validated autonomy; scientific instruments share a robust mobility platform.','Communication latency, radiation, dust and one-way recovery make testing unusually demanding.','Learn fault tolerance, state machines, visual odometry and operations planning.','NASA systems engineering · JPL AutoNav · planetary datasets')},
{id:'delivery',name:'Kibo Rover',type:'Service',application:'Last-mile delivery',difficulty:'Intermediate',icon:'▣',description:'A concept urban rover that combines safe navigation with human-friendly interaction.',tags:['Mobile','Service'],specs:{dof:'2 drive',sensors:'LiDAR · GPS · ultrasonic',controller:'Edge AI computer',power:'48V battery',payload:'25 kg'},features:['Geofenced navigation','Obstacle avoidance','Fleet telemetry'],...detail('A teaching concept for a low-speed delivery robot operating on mapped sidewalks and shared public spaces.','Localization blends GNSS, LiDAR and wheel odometry; a behavior tree handles crossings, yielding and handoff states.','Campus logistics, groceries, hospital supplies and warehouse-to-door routes.','Repeatable routes; remote fleet monitoring; low operating cost per delivery.','Weather, accessibility, pedestrians and local regulations constrain deployment.','Study behavior trees, geofencing, fleet observability and human-robot interaction.','Nav2 · OpenStreetMap · behavior-tree design')}
];

export const components=[
{id:'arduino',name:'Arduino Uno R4',category:'Microcontrollers',icon:'▦',description:'A friendly 32-bit development board for prototyping sensors, motors and interactive machines.',stats:['5V logic','14 GPIO','C/C++'],principle:'The microcontroller executes a loop of instructions and reads or drives pins in real time.',applications:'Education · prototypes · control panels',...detail('A beginner-friendly board that turns an electrical idea into a repeatable embedded experiment.','Firmware samples inputs, runs control logic and updates outputs at deterministic intervals; peripherals handle timing and serial communication.','Motor demos, sensor calibration, classroom robots and quick proof-of-concepts.','Low barrier to entry; huge library ecosystem; easy serial debugging.','Limited RAM and compute; no built-in wireless; GPIO current must be respected.','Learn voltage levels, digital/analog IO, interrupts, PWM and debouncing.','Arduino IDE · Uno R4 docs · serial monitor')},
{id:'esp32',name:'ESP32',category:'Microcontrollers',icon:'⌁',description:'Connected dual-core MCU with Wi-Fi, Bluetooth and excellent low-power modes.',stats:['3.3V logic','Wi-Fi + BLE','34 GPIO'],principle:'A system-on-chip combines processing, radio and peripherals for connected edge devices.',applications:'IoT robots · telemetry · wearables',...detail('A connected microcontroller for robots that need telemetry, remote commands or distributed sensing.','A real-time firmware task samples hardware while network tasks publish state over Wi-Fi, BLE or MQTT.','Fleet beacons, remote controllers, environmental nodes and smart actuators.','Wireless built in; low cost; deep sleep enables battery operation.','3.3 V pins are not 5 V tolerant; radio timing and network outages need defensive design.','Study FreeRTOS tasks, MQTT, watchdogs, power budgets and secure provisioning.','ESP-IDF · Arduino core · MQTT')},
{id:'jetson',name:'NVIDIA Jetson Orin Nano',category:'Computing',icon:'◫',description:'Compact edge AI computer for computer vision, neural inference and ROS2 workloads.',stats:['8GB LPDDR5','GPU acceleration','CSI cameras'],principle:'Parallel GPU cores run vision and ML models locally with low latency.',applications:'Vision robots · drones · autonomy',...detail('A Linux edge computer for workloads that exceed a microcontroller: vision, planning, logging and model inference.','Camera frames enter a hardware-accelerated pipeline; optimized models produce detections that a ROS 2 node turns into decisions.','Object detection, depth processing, multi-camera robots and simulation-to-real deployment.','Low latency offline inference; CUDA ecosystem; rich I/O.','Power, thermal limits and model optimization matter; it is not a safety controller.','Learn Linux services, ROS 2 composition, profiling, TensorRT and camera calibration.','JetPack · CUDA · TensorRT · ROS 2')},
{id:'l298n',name:'L298N Motor Driver',category:'Motor Drivers',icon:'↔',description:'Dual H-bridge module for controlling the direction and speed of two brushed DC motors.',stats:['5–35V motor','2A peak','2 channels'],principle:'An H-bridge reverses current through a motor while PWM controls average power.',applications:'Rovers · arms · pan-tilt rigs',...detail('A classic driver board that separates low-power logic signals from the higher current needed by brushed motors.','Transistor bridges switch polarity; PWM changes effective voltage while flyback paths protect the switching stage.','Two-wheel rovers, conveyor prototypes and small pan-tilt mechanisms.','Inexpensive; easy direction and speed interface; widely documented.','Voltage drop wastes power; thermal limits are significant; peak current is not continuous rating.','Learn motor current, flyback, PWM frequency, grounding and battery protection.','Datasheet · oscilloscope PWM lab · motor sizing worksheet')},
{id:'raspberry-pi',name:'Raspberry Pi 5',category:'Computing',icon:'▤',description:'Linux computer with GPIO and camera interfaces for robotics orchestration.',stats:['Quad-core ARM','40-pin GPIO','Gigabit Ethernet'],principle:'Runs a full operating system, coordinating high-level behaviors and network services.',applications:'ROS2 · dashboards · simulation',...detail('A general-purpose Linux computer for robot applications, operator interfaces and networked experiments.','Processes run as services and exchange messages; GPIO and camera drivers connect the digital system to hardware.','ROS 2 robots, web dashboards, data loggers and classroom simulators.','Low cost; familiar Linux tools; large community and accessory ecosystem.','Non-real-time scheduling and SD-card reliability require buffering and careful architecture.','Learn Linux, Python packaging, systemd, GPIO safety and ROS 2 launch files.','Raspberry Pi OS · libcamera · systemd')}
];

export const sensors=[
{id:'lidar',name:'2D LiDAR',category:'Range',icon:'◎',description:'Sweeps laser pulses across a plane to produce accurate distance measurements.',output:'Polar point cloud',use:'SLAM · obstacle avoidance',spec:'Typical demo range: 12m',example:'Build a map with ROS2 slam_toolbox.',...detail('A rotating laser rangefinder gives a robot a geometric slice of its surroundings.', 'Time-of-flight or phase measurements become angle-distance samples; filtering and TF alignment make scans useful to mapping.', 'Indoor mapping, corridor following, docking and obstacle layers.', 'Accurate geometry; works in low light; predictable data rate.', 'Glass, reflective surfaces, dust and a single scan plane can create blind spots.', 'Study scan frames, filtering, odometry, occupancy grids and scan matching.', 'LaserScan · SLAM Toolbox · RViz')},
{id:'ultrasonic',name:'Ultrasonic HC-SR04',category:'Range',icon:'◌',description:'Times an ultrasonic echo to estimate distance to nearby objects.',output:'Digital pulse width',use:'Parking sensors · line robots',spec:'Typical demo range: 2–400cm',example:'Trigger, echo, divide flight time by two.',...detail('A simple time-of-flight sensor for close-range presence and collision experiments.', 'A short acoustic burst reflects from a surface; the echo duration is converted to distance using the speed of sound.', 'Bumper backup, bin-level sensing and beginner obstacle avoidance.', 'Very inexpensive; simple interface; no camera processing required.', 'Soft or angled surfaces absorb sound; readings are slow and noisy near other sensors.', 'Learn timing diagrams, median filters, GPIO voltage levels and sensor placement.', 'HC-SR04 datasheet · GPIO timing lab')},
{id:'imu',name:'6-axis IMU',category:'Motion',icon:'⌁',description:'Combines accelerometer and gyroscope data to estimate motion and orientation.',output:'Acceleration + angular velocity',use:'Balancing · dead reckoning',spec:'3-axis accel + 3-axis gyro',example:'Fuse readings with a complementary filter.',...detail('An inertial measurement unit provides fast motion clues when external landmarks are unavailable.', 'Gyroscopes integrate angular velocity while accelerometers measure gravity and specific force; fusion limits drift.', 'Balancing, attitude estimation, vibration monitoring and odometry assistance.', 'High update rate; compact; works without light or GPS.', 'Bias drift, vibration and magnetic/linear acceleration ambiguity require calibration and fusion.', 'Study frames, bias estimation, complementary and Kalman filters.', 'sensor_msgs/Imu · Madgwick filter · calibration routine')},
{id:'camera',name:'Depth Camera',category:'Vision',icon:'▣',description:'Pairs image sensing with per-pixel depth for rich 3D perception.',output:'RGB + depth frames',use:'Manipulation · navigation',spec:'USB/CSI · synchronized frames',example:'Detect objects and project pixels into 3D.',...detail('A synchronized RGB and depth sensor gives robots appearance plus approximate 3D structure.', 'Calibration maps pixels to rays; stereo or active depth estimates distance, then vision models label objects.', 'Pick-and-place, people-aware navigation and tabletop reconstruction.', 'Rich semantic information; useful for manipulation; easy visualization.', 'Sunlight, transparent objects and bandwidth can degrade depth; privacy and compute need consideration.', 'Learn camera models, calibration, point clouds, detection and frame transforms.', 'OpenCV · DepthAI · image_pipeline')}
];

export const actuators=[
{id:'dc-motor',name:'DC Motor',type:'Rotary',control:'PWM + H-bridge',use:'Wheeled drive',description:'Continuous rotation motor with simple speed control.',...detail('A brushed motor converts electrical current into continuous shaft rotation.', 'Magnetic torque scales with current; back-EMF rises with speed, so a driver and feedback loop regulate motion.', 'Wheeled bases, fans, pumps and lightweight mechanisms.','Simple, cheap and easy to source; high speed options.','Open-loop speed varies with load; brushes wear; stall current can damage electronics.','Learn current limits, encoders, PWM, gearing and velocity PID.','Motor datasheet · encoder lab')},
{id:'servo-motor',name:'Servo Motor',type:'Rotary',control:'Pulse position',use:'Joints · pan/tilt',description:'Integrated feedback and gearbox provide repeatable angular position.',...detail('A hobby or smart servo packages motor, gearbox, controller and position feedback.', 'The internal controller compares commanded angle with a potentiometer or encoder and drives the motor to reduce error.', 'Grippers, camera gimbals, small arms and educational joints.','Position control is built in; compact wiring; easy command interface.','Limited travel, backlash and stall heating; torque varies with voltage and speed.','Learn pulse timing, torque margins, mechanical stops and closed-loop error.','Servo calibration worksheet · PWM scope lab')},
{id:'stepper-motor',name:'Stepper Motor',type:'Rotary',control:'Step/direction',use:'CNC · precise stages',description:'Moves in discrete steps with strong holding torque.',...detail('A stepper creates predictable angular increments by energizing coils in sequence.', 'A driver microsteps phase currents and an open-loop controller counts pulses to estimate position.', '3D printers, camera sliders, valves and indexing tables.','Good low-speed positioning; strong holding torque; straightforward planning.','Can lose steps under load; resonance and heat need management; inefficient at speed.','Study acceleration ramps, microstepping, homing switches and torque curves.','A4988/TMC drivers · motion profile lab')},
{id:'linear-actuator',name:'Linear Actuator',type:'Linear',control:'Driver + feedback',use:'Lifting · grippers',description:'Converts rotary motion into controlled linear travel.',...detail('A linear actuator extends or retracts a rod to push, pull, lift or clamp a mechanism.', 'A screw, belt or voice coil transforms motor torque into linear force; limit switches and feedback define safe travel.', 'Lifts, adjustable fixtures, grippers and assistive devices.','Direct force along an axis; easy mechanical packaging; many stroke options.','Slower than rotary drives; pinch hazards; force and duty cycle are limited.','Learn lead screw ratio, load paths, limit switches and emergency stops.','Actuator sizing guide · safety interlock lab')}
];

export const projects=[
{id:'line-follower',name:'Line Following Rover',level:'Beginner',time:'1 weekend',description:'Build a sensor-guided rover that follows a track using proportional correction.',tools:['Arduino','IR sensors','DC motors'],steps:['Wire two reflectance sensors','Calibrate black/white readings','Tune proportional steering','Test on curved track'],outcomes:['Explain reflectance thresholds','Tune a feedback loop','Record repeatable test runs'],...detail('A first control project where noisy sensor readings become a smooth steering command.','The controller compares left and right reflectance error, then adjusts motor PWM proportionally.', 'Educational tracks, warehouse line concepts and PID practice.','Fast feedback; visible behavior; inexpensive parts.','Lighting, wheel mismatch and sensor height affect results.','Add integral/derivative terms only after proportional behavior is stable.','Arduino sketch · wiring diagram · test log template')},
{id:'ros2-nav',name:'ROS2 Autonomous Rover',level:'Advanced',time:'3–5 weeks',description:'Map a room and navigate goals using a LiDAR-equipped mobile base.',tools:['ROS2 Jazzy','Nav2','LiDAR'],steps:['Create a colcon workspace','Launch sensor drivers','Build a map with SLAM','Send navigation goals'],outcomes:['Inspect a ROS graph','Create a map and save it','Tune costmaps safely'],...detail('An end-to-end autonomy build connecting drivers, transforms, localization, planning and motor control.','SLAM or localization estimates pose; Nav2 layers obstacles into a costmap and sends a trajectory to a controller.', 'Indoor delivery demos, mapping labs and research prototypes.','Modular architecture; observable messages; concepts transfer to larger robots.','TF mistakes, wheel slip and poor maps can make debugging non-obvious.','Work in simulation first, then validate each sensor and frame on hardware.','ROS 2 Jazzy · Nav2 · Gazebo Harmonic')},
{id:'vision-arm',name:'Vision Pick & Place',level:'Intermediate',time:'2 weeks',description:'Use a camera and arm to identify colored parts and place them in bins.',tools:['Python','OpenCV','Servo arm'],steps:['Capture and threshold colors','Calibrate camera frame','Plan safe pick pose','Run closed-loop sorting'],outcomes:['Calibrate pixels to millimeters','Use confidence thresholds','Add a recovery state'],...detail('A compact manipulation project that turns image pixels into a safe, repeatable arm motion.','Color segmentation proposes an object centroid; calibrated transforms map it to a reachable pose and a state machine closes the loop.', 'Sorting, inspection and lab automation.','Combines vision, geometry, control and recovery behavior in one demo.','Lighting changes, occlusion and servo backlash require robust thresholds.','Start with a fixed camera and known plane before adding depth or tracking.','OpenCV · MoveIt 2 · camera calibration')}
];

export const quiz=[
{q:'Which protocol is commonly used for short sensor connections?',options:['I2C','HTTP','HDMI','FTP'],answer:'I2C',explain:'I2C uses two wires and addresses multiple devices on the same bus.',topic:'electronics'},
{q:'What does PWM control on a DC motor?',options:['Average voltage and speed','GPS position','Camera focus','Battery chemistry'],answer:'Average voltage and speed',explain:'Pulse width changes average power delivered by a driver.',topic:'control'},
{q:'What is ROS2 primarily?',options:['A robotics middleware','A motor type','A battery standard','A CAD format'],answer:'A robotics middleware',explain:'ROS2 provides communication, tooling and conventions for robot software.',topic:'ros2'},
{q:'Which sensor is best suited for 2D mapping?',options:['LiDAR','PIR','Thermistor','Relay'],answer:'LiDAR',explain:'LiDAR produces accurate range scans used by SLAM algorithms.',topic:'navigation'},
{q:'Why is a common reference ground important?',options:['It gives signals a shared voltage reference','It increases battery capacity','It cools motors','It encrypts telemetry'],answer:'It gives signals a shared voltage reference',explain:'Without a shared reference, a digital high or low can be interpreted unpredictably.',topic:'electronics'},
{q:'What does TF2 maintain in a ROS 2 system?',options:['Coordinate-frame relationships','Motor temperature','User passwords','CAD meshes'],answer:'Coordinate-frame relationships',explain:'TF2 lets nodes transform measurements between time-stamped frames.',topic:'ros2'}
];
export const careers=[
{id:'software',name:'Robotics Software Engineer',skills:'C++, Python, ROS2, algorithms',roadmap:'Programming → ROS2 → perception → navigation',salary:'Systems and autonomy teams',day:'Build nodes, debug logs, review algorithms and integrate hardware.',...detail('Software engineers make sensing, planning and behavior reliable on a real machine.','They turn algorithms into observable, testable nodes with clear timing and failure behavior.','Autonomy, manipulation, fleet platforms and simulation.','High leverage across many robot platforms; strong open-source ecosystem.','Hardware timing, flaky sensors and safety requirements complicate debugging.','Ship a ROS 2 package, add tests, simulate it and document its interfaces.','ROS 2 docs · Navigation2 · robotics coding exercises')},
{id:'embedded',name:'Embedded Engineer',skills:'C, electronics, RTOS, debugging',roadmap:'Circuits → microcontrollers → drivers → real-time systems',salary:'Firmware and platform teams',day:'Bring up boards, write drivers, measure signals and protect hardware.',...detail('Embedded engineers connect deterministic code to motors, sensors, power and safety circuits.','Interrupts, timers and RTOS tasks schedule work while drivers enforce electrical and timing contracts.','Motor control, wearable robots, safety controllers and sensor platforms.','Direct hardware impact; efficient systems; foundational robotics knowledge.','Resource limits, electrical faults and timing bugs can be difficult to reproduce.','Build a sensor driver, measure it with a scope and add a hardware-in-the-loop test.','FreeRTOS · datasheets · oscilloscope practice')},
{id:'vision',name:'Computer Vision Engineer',skills:'Python, OpenCV, PyTorch, geometry',roadmap:'Linear algebra → image processing → deep learning → deployment',salary:'Perception and AI teams',day:'Curate data, train models, analyze failure cases and optimize inference.',...detail('Vision engineers help robots understand objects, surfaces and people from images or depth.', 'Geometry handles calibration and projection; learned models classify or segment uncertain visual patterns.', 'Inspection, picking, navigation and human-aware interaction.','Transforms raw pixels into useful geometry and decisions.','Data bias, lighting variation, latency and confidence calibration matter.','Create a small labeled dataset, establish a baseline and measure edge cases.','OpenCV · PyTorch · TensorRT')},
{id:'automation',name:'Automation Engineer',skills:'PLC, controls, industrial networks',roadmap:'Control theory → PLCs → safety → factory integration',salary:'Manufacturing and systems integrators',day:'Design cells, validate sequences, commission equipment and improve throughput.',...detail('Automation engineers make repeatable production systems safe, maintainable and measurable.', 'PLC state machines coordinate sensors, actuators and safety interlocks with deterministic scan cycles.', 'Packaging, welding, inspection and material handling.','Direct operational value; combines mechanics, controls and people.','Commissioning schedules, legacy networks and safety compliance add constraints.','Learn ladder logic, risk assessment, cycle-time analysis and traceability.','IEC 61131 · PLC simulators · functional safety')}
];
export const glossary=[
['Actuator','A device that turns an energy signal into physical motion.'],['Degrees of Freedom','Independent axes of movement a robot can control.'],['GPIO','General-purpose pins used for digital input and output.'],['LiDAR','Light detection and ranging using laser time-of-flight.'],['Odometry','An estimate of motion from wheel, visual or inertial measurements.'],['PID','Feedback controller using proportional, integral and derivative terms.'],['ROS2','Open robotics middleware for distributed robot systems.'],['SLAM','Simultaneous localization and mapping from sensor data.'],['TF2','A ROS 2 library for time-aware coordinate-frame transforms.'],['Torque','Rotational force that produces angular acceleration.'],['URDF','XML description of a robot’s links, joints and visual/collision geometry.'],['Workspace','A bounded environment or software build area where a robot operates.']
];
export const topics={
programming:{title:'Programming for robots',eyebrow:'Build the brain',intro:'Move from first variables to reliable autonomous behaviors.',cards:[['C / C++','Firmware, drivers and high-performance robot nodes.','Memory, timing and interfaces'],['Python','Rapid prototyping, APIs, data and AI pipelines.','Readable experiments and tooling'],['MATLAB','Model control systems and analyze experiments.','Simulation before hardware'],['Computer Vision','Turn pixels into geometry and decisions.','Images, calibration and inference']]},
ros2:{title:'ROS2 command center',eyebrow:'Connect the system',intro:'Learn nodes, topics, services, actions, TF and Nav2 through a practical roadmap.',cards:[['Nodes & topics','Small processes exchange typed messages over a graph.','Inspect with ros2 topic'],['TF2','Keep every sensor and joint frame consistent.','Draw the frame tree'],['Launch & bags','Reproduce complete robot experiments.','Record before tuning'],['Navigation','Combine localization, planning and control.','Validate in simulation']]},
ai:{title:'AI in robotics',eyebrow:'Perceive · reason · act',intro:'Deploy machine learning where the physical world is uncertain.',cards:[['Perception','Detection, segmentation and depth make scenes actionable.','Measure confidence'],['Learning','Train models with representative data and careful evaluation.','Split data by scene'],['Decision making','Policies choose actions under constraints and uncertainty.','Add recovery states'],['Edge deployment','Optimize models for real-time compute on the robot.','Profile end to end']]},
navigation:{title:'Robot navigation',eyebrow:'Find the safe path',intro:'From localization and maps to planning and obstacle avoidance.',cards:[['Localization','Estimate pose from odometry and landmarks.','Track drift'],['SLAM','Build a map while tracking movement.','Check loop closures'],['Planning','A* and sampling methods choose feasible routes.','Respect footprint'],['Control','PID and trajectory tracking turn plans into motion.','Tune on a safe track']]}
};
