export const robots=[
{id:'atlas',name:'Atlas',type:'Humanoid',application:'Industrial mobility',difficulty:'Advanced',icon:'?',description:'A dynamic humanoid platform built for balance, manipulation and human-centric workspaces.',tags:['Humanoid','AI'],specs:{dof:'28+',sensors:'LiDAR · IMU · stereo vision',controller:'Real-time robot control',power:'Battery electric'},features:['Dynamic whole-body control','Terrain-aware perception','Force-sensitive manipulation']},
{id:'spot',name:'Spot',type:'Legged',application:'Inspection & autonomy',difficulty:'Advanced',icon:'?',description:'An agile quadruped that carries sensing payloads into places wheeled robots cannot reach.',tags:['Legged','Autonomous'],specs:{dof:'12',sensors:'Depth · IMU · cameras',controller:'Autonomy stack',power:'Rechargeable battery'},features:['API-first autonomy','Self-righting mobility','Payload ecosystem']},
{id:'turtlebot',name:'TurtleBot 4',type:'Wheeled',application:'ROS2 education',difficulty:'Beginner',icon:'?',description:'The approachable mobile base for learning ROS2, navigation and mapping hands-on.',tags:['Educational','ROS2'],specs:{dof:'2 drive + caster',sensors:'2D LiDAR · depth camera',controller:'Raspberry Pi 4',power:'Li-ion battery'},features:['Nav2 ready','Open-source ROS2 stack','Modular accessories']},
{id:'ur5',name:'UR5e',type:'Robotic Arm',application:'Assembly & research',difficulty:'Intermediate',icon:'?',description:'Collaborative six-axis arm for precise assembly, teaching and flexible automation.',tags:['Industrial','Arm'],specs:{dof:'6',sensors:'Joint torque feedback',controller:'Dedicated cabinet',power:'AC mains'},features:['Force limiting','Tool center point control','Fast deployment']},
{id:'perseverance',name:'Perseverance',type:'Space',application:'Planetary science',difficulty:'Expert',icon:'?',description:'A resilient autonomous rover designed to navigate and investigate the Martian surface.',tags:['Space','Autonomous'],specs:{dof:'6 wheel drive',sensors:'Cameras · spectrometers',controller:'Radiation-hardened compute',power:'MMRTG'},features:['Autonomous traverse','Sample caching','Long-range communications']},
{id:'delivery',name:'Kibo Rover',type:'Service',application:'Last-mile delivery',difficulty:'Intermediate',icon:'?',description:'A concept urban rover that combines safe navigation with human-friendly interaction.',tags:['Mobile','Service'],specs:{dof:'2 drive',sensors:'LiDAR · GPS · ultrasonic',controller:'Edge AI computer',power:'48V battery'},features:['Geofenced navigation','Obstacle avoidance','Fleet telemetry']}
];
export const components=[
{id:'arduino',name:'Arduino Uno R4',category:'Microcontrollers',icon:'?',description:'A friendly 32-bit development board for prototyping sensors, motors and interactive machines.',stats:['5V logic','14 GPIO','C/C++'],principle:'The microcontroller executes a loop of instructions and reads or drives pins in real time.',applications:'Education · prototypes · control panels'},
{id:'esp32',name:'ESP32',category:'Microcontrollers',icon:'?',description:'Connected dual-core MCU with Wi-Fi, Bluetooth and excellent low-power modes.',stats:['3.3V logic','Wi-Fi + BLE','34 GPIO'],principle:'A system-on-chip combines processing, radio and peripherals for connected edge devices.',applications:'IoT robots · telemetry · wearables'},
{id:'jetson',name:'NVIDIA Jetson Orin Nano',category:'Computing',icon:'?',description:'Compact edge AI computer for computer vision, neural inference and ROS2 workloads.',stats:['8GB LPDDR5','GPU acceleration','CSI cameras'],principle:'Parallel GPU cores run vision and ML models locally with low latency.',applications:'Vision robots · drones · autonomy'},
{id:'l298n',name:'L298N Motor Driver',category:'Motor Drivers',icon:'?',description:'Dual H-bridge module for controlling the direction and speed of two brushed DC motors.',stats:['5–35V motor','2A peak','2 channels'],principle:'An H-bridge reverses current through a motor while PWM controls average power.',applications:'Rovers · arms · pan-tilt rigs'},
{id:'raspberry-pi',name:'Raspberry Pi 5',category:'Computing',icon:'?',description:'Linux computer with GPIO and camera interfaces for robotics orchestration.',stats:['Quad-core ARM','40-pin GPIO','Gigabit Ethernet'],principle:'Runs a full operating system, coordinating high-level behaviors and network services.',applications:'ROS2 · dashboards · simulation'}
];
export const sensors=[
{id:'lidar',name:'2D LiDAR',category:'Range',icon:'?',description:'Sweeps laser pulses across a plane to produce accurate distance measurements.',output:'Polar point cloud',use:'SLAM · obstacle avoidance',spec:'Typical demo range: 12m',example:'Build a map with ROS2 slam_toolbox.'},
{id:'ultrasonic',name:'Ultrasonic HC-SR04',category:'Range',icon:'?',description:'Times an ultrasonic echo to estimate distance to nearby objects.',output:'Digital pulse width',use:'Parking sensors · line robots',spec:'Typical demo range: 2–400cm',example:'Trigger, echo, divide flight time by two.'},
{id:'imu',name:'6-axis IMU',category:'Motion',icon:'?',description:'Combines accelerometer and gyroscope data to estimate motion and orientation.',output:'Acceleration + angular velocity',use:'Balancing · dead reckoning',spec:'3-axis accel + 3-axis gyro',example:'Fuse readings with a complementary filter.'},
{id:'camera',name:'Depth Camera',category:'Vision',icon:'?',description:'Pairs image sensing with per-pixel depth for rich 3D perception.',output:'RGB + depth frames',use:'Manipulation · navigation',spec:'USB/CSI · synchronized frames',example:'Detect objects and project pixels into 3D.'}
];
export const actuators=[{name:'DC Motor',type:'Rotary',control:'PWM + H-bridge',use:'Wheeled drive',description:'Continuous rotation motor with simple speed control.'},{name:'Servo Motor',type:'Rotary',control:'Pulse position',use:'Joints · pan/tilt',description:'Integrated feedback and gearbox provide repeatable angular position.'},{name:'Stepper Motor',type:'Rotary',control:'Step/direction',use:'CNC · precise stages',description:'Moves in discrete steps with strong holding torque.'},{name:'Linear Actuator',type:'Linear',control:'Driver + feedback',use:'Lifting · grippers',description:'Converts rotary motion into controlled linear travel.'}];
export const projects=[{id:'line-follower',name:'Line Following Rover',level:'Beginner',time:'1 weekend',description:'Build a sensor-guided rover that follows a track using proportional correction.',tools:['Arduino','IR sensors','DC motors'],steps:['Wire two reflectance sensors','Calibrate black/white readings','Tune proportional steering','Test on curved track']},{id:'ros2-nav',name:'ROS2 Autonomous Rover',level:'Advanced',time:'3–5 weeks',description:'Map a room and navigate goals using a LiDAR-equipped mobile base.',tools:['ROS2 Jazzy','Nav2','LiDAR'],steps:['Create a colcon workspace','Launch sensor drivers','Build a map with SLAM','Send navigation goals']},{id:'vision-arm',name:'Vision Pick & Place',level:'Intermediate',time:'2 weeks',description:'Use a camera and arm to identify colored parts and place them in bins.',tools:['Python','OpenCV','Servo arm'],steps:['Capture and threshold colors','Calibrate camera frame','Plan safe pick pose','Run closed-loop sorting']}];
export const quiz=[{q:'Which protocol is commonly used for short sensor connections?',options:['I2C','HTTP','HDMI','FTP'],answer:'I2C',explain:'I2C uses two wires and addresses multiple devices on the same bus.'},{q:'What does PWM control on a DC motor?',options:['Average voltage and speed','GPS position','Camera focus','Battery chemistry'],answer:'Average voltage and speed',explain:'Pulse width changes average power delivered by a driver.'},{q:'What is ROS2 primarily?',options:['A robotics middleware','A motor type','A battery standard','A CAD format'],answer:'A robotics middleware',explain:'ROS2 provides communication, tooling and conventions for robot software.'},{q:'Which sensor is best suited for 2D mapping?',options:['LiDAR','PIR','Thermistor','Relay'],answer:'LiDAR',explain:'LiDAR produces accurate range scans used by SLAM algorithms.'}];
export const careers=[{name:'Robotics Software Engineer',skills:'C++, Python, ROS2, algorithms',roadmap:'Programming ? ROS2 ? perception ? navigation'},{name:'Embedded Engineer',skills:'C, electronics, RTOS, debugging',roadmap:'Circuits ? microcontrollers ? drivers ? real-time systems'},{name:'Computer Vision Engineer',skills:'Python, OpenCV, PyTorch, geometry',roadmap:'Linear algebra ? image processing ? deep learning ? deployment'},{name:'Automation Engineer',skills:'PLC, controls, industrial networks',roadmap:'Control theory ? PLCs ? safety ? factory integration'}];
export const glossary=[['Actuator','A device that turns an energy signal into physical motion.'],['Degrees of Freedom','Independent axes of movement a robot can control.'],['GPIO','General-purpose pins used for digital input and output.'],['LiDAR','Light detection and ranging using laser time-of-flight.'],['PID','Feedback controller using proportional, integral and derivative terms.'],['ROS2','Open robotics middleware for distributed robot systems.'],['SLAM','Simultaneous localization and mapping from sensor data.'],['Torque','Rotational force that produces angular acceleration.']];
export const topics={programming:{title:'Programming for robots',eyebrow:'Build the brain',intro:'Move from first variables to reliable autonomous behaviors.',cards:[['C / C++','Firmware, drivers and high-performance robot nodes.'],['Python','Rapid prototyping, APIs, data and AI pipelines.'],['MATLAB','Model control systems and analyze experiments.'],['Computer Vision','Turn pixels into geometry and decisions.']]},ros2:{title:'ROS2 command center',eyebrow:'Connect the system',intro:'Learn nodes, topics, services, actions, TF and Nav2 through a practical roadmap.',cards:[['Nodes & topics','Small processes exchange typed messages over a graph.'],['TF2','Keep every sensor and joint frame consistent.'],['Launch & bags','Reproduce complete robot experiments.'],['Navigation','Combine localization, planning and control.']]},ai:{title:'AI in robotics',eyebrow:'Perceive · reason · act',intro:'Deploy machine learning where the physical world is uncertain.',cards:[['Perception','Detection, segmentation and depth make scenes actionable.'],['Learning','Train models with representative data and careful evaluation.'],['Decision making','Policies choose actions under constraints and uncertainty.'],['Edge deployment','Optimize models for real-time compute on the robot.']]},navigation:{title:'Robot navigation',eyebrow:'Find the safe path',intro:'From localization and maps to planning and obstacle avoidance.',cards:[['Localization','Estimate pose from odometry and landmarks.'],['SLAM','Build a map while tracking movement.'],['Planning','A* and sampling methods choose feasible routes.'],['Control','PID and trajectory tracking turn plans into motion.']]}};
